CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=n
CONFIG_ZMK_EXT_POWER=y
CONFIG_PMW3610=y
CONFIG_PMW3610_SWAP_XY=y
CONFIG_PMW3610_INVERT_X=y
CONFIG_PMW3610_INVERT_Y=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=3264
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=20
CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=300

# --- peripheral: no USB, no Studio RPC, but relay settings/split events to the central ---
CONFIG_ZMK_USB=n
CONFIG_SETTINGS=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
CONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=240
CONFIG_ZMK_PMW3610_SPLIT_RPC_RELAY=y
CONFIG_ZMK_CUSTOM_SETTINGS=y
CONFIG_ZMK_CUSTOM_SETTINGS_SPLIT_RPC_RELAY=y
CONFIG_ZMK_PMW3610_CUSTOM_SETTINGS=y
